Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "db01"
  config.vm.network "private_network", ip:"192.168.2.9"
  config.vm.network "forwarded_port", guest: 3307, host: 3307
  config.vm.provision "shell", path: "provision.sh"
end